export enum UserFormActionType {
  SHOW_FORM,
  HIDE_FORM,
  SET_ENTERED_NAME,
  TOUCHED_NAME,
  SUBMIT_FORM,
  SET_ENTERED_PAYMENT_DETAILS,
  SUBMIT_EDIT_FORM,
  CANCEL_EDIT_FORM,
  RENDER_FORM,
  SHOW_DELETE_ERROR,
  HIDE_DELETE_ERROR,
}
